"""
adapters/context_builder.py  –  AI-consumable context builder
───────────────────────────────────────────────────────────────
Packages financial data from the database into structured JSON
that can be passed to any LLM (Perplexity, Claude, GPT-4, etc.)
for analysis, Q&A, or further intelligence.

Usage:
    from adapters.context_builder import build_context, save_context
    ctx = build_context(entity_id, period="2025-01")
    save_context(ctx, Path("context_2025-01.json"))

The JSON is also what the GitHub/AI consumption mode uses:
    "Pass this file to any AI: https://github.com/your-org/fi/blob/main/context.json"
"""
from __future__ import annotations

import json
from decimal import Decimal
from pathlib import Path
from typing import Any, Dict, Optional


class _DecimalEncoder(json.JSONEncoder):
    def default(self, obj: Any) -> Any:
        if isinstance(obj, Decimal):
            return float(obj)
        return super().default(obj)


def build_context(
        entity_id: str,
        period: Optional[str] = None,
        include_transactions: bool = True,
        include_positions: bool = True,
) -> Dict[str, Any]:
    """
    Build a rich AI-consumable context dict for one entity + period.

    Returns a dict with:
      - entity: entity metadata
      - period: statement period
      - balance_sheet: full balance sheet breakdown
      - transactions: list of transactions (if include_transactions=True)
      - positions: brokerage positions (if include_positions=True)
      - tax_estimate: annual tax obligation estimate
      - summary: high-level KPIs
      - ai_instructions: system prompt snippet for LLMs
    """
    from ledger_agent.core.database import EntityRepo, SnapshotRepo, TransactionRepo
    from ledger_agent.core.accounting.balance_sheet import BalanceSheetBuilder
    from ledger_agent.core.accounting.tax_estimator import TaxEstimator

    # Resolve entity
    entities = EntityRepo.list_all()
    entity = next((e for e in entities if e.id == entity_id), None)
    if entity is None:
        raise ValueError(f"Entity not found: {entity_id}")

    # Resolve period
    snapshots = SnapshotRepo.list_for_entity(entity_id)
    available = sorted({s.statement_period for s in snapshots}, reverse=True)
    if not available:
        raise ValueError("No imported statements found for this entity.")
    period = period or available[0]

    # Build balance sheet
    bs = BalanceSheetBuilder(entity_id, period).build()

    # Build tax estimate
    tax = TaxEstimator(entity.name, int(period[:4])).estimate_from_balance_sheet(bs)

    # Build context
    ctx: Dict[str, Any] = {
        "schema_version": "2.0",
        "generated_at": _now_iso(),
        "entity": {
            "name": entity.name,
            "type": entity.entity_type,
            "state": entity.state,
        },
        "period": period,
        "available_periods": available,
        "balance_sheet": {
            "total_assets": float(bs.total_assets),
            "total_liabilities": float(bs.total_liabilities),
            "total_equity": float(bs.total_equity),
            "net_income": float(bs.net_income),
            "is_balanced": bs.is_balanced,
            "lines": [
                {
                    "coa_code": line.coa_code,
                    "label": line.label,
                    "amount": float(line.amount),
                    "type": line.coa_type.value,
                    "is_subtotal": line.is_subtotal,
                    "indent": line.indent,
                }
                for line in bs.lines
            ],
        },
        "tax_estimate": {
            "annual_net_income": float(tax.net_income),
            "se_tax": float(tax.se_tax),
            "federal_income_tax": float(tax.federal_income_tax),
            "state_income_tax": float(tax.state_income_tax),
            "total_annual_tax": float(tax.total_annual_tax),
            "effective_rate_pct": float(tax.effective_rate),
            "quarterly_payments": [
                {
                    "quarter": pmt.quarter,
                    "due_date": pmt.due_date,
                    "amount": float(pmt.amount),
                }
                for pmt in tax.quarterly_payments
            ],
        },
        "summary": {
            "net_income": float(bs.net_income),
            "total_assets": float(bs.total_assets),
            "total_liabilities": float(bs.total_liabilities),
            "debt_to_equity": _safe_div(bs.total_liabilities, bs.total_equity),
        },
        "ai_instructions": (
            f"You are analyzing financial data for {entity.name} ({entity.entity_type}), "
            f"period {period}. "
            f"Net income: ${float(bs.net_income):,.2f}. "
            f"Total assets: ${float(bs.total_assets):,.2f}. "
            f"This data was generated by FinancialIntelligence. "
            f"Answer questions accurately using the data provided."
        ),
    }

    # Optionally include transactions — descriptions redacted for AI export (R-46)
    if include_transactions:
        txns = TransactionRepo.list_for_period(period)
        try:
            from ledger_agent.core.privacy import redact as _redact
        except Exception:
            _redact = None  # type: ignore[assignment]

        txn_records = []
        for t in txns:
            desc = t.description
            if _redact is not None:
                try:
                    desc, _ = _redact(desc, scope="ai_context")
                except Exception:
                    pass  # Never block export on privacy error
            txn_records.append({
                "date": t.date.isoformat(),
                "description": desc,
                "amount": float(t.amount),
                "coa_code": t.coa_code,
                "type": t.transaction_type.value if t.transaction_type else None,
                "is_transfer": t.is_transfer,
            })
        ctx["transactions"] = txn_records

    # Optionally include positions
    if include_positions:
        from ledger_agent.core.database import AccountRepo, PositionRepo
        accounts = AccountRepo.list_for_entity(entity_id)
        all_positions = []
        for acct in accounts:
            positions = PositionRepo.list_for_period(acct.id, period)
            for p in positions:
                all_positions.append({
                    "account": f"{acct.institution} – {acct.name}",
                    "symbol": p.symbol,
                    "quantity": float(p.quantity),
                    "price": float(p.price_per_unit),
                    "market_value": float(p.market_value),
                })
        ctx["positions"] = all_positions

    return ctx


def save_context(ctx: Dict[str, Any], path: Path) -> Path:
    """Save context dict as pretty-printed JSON. Returns the file path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(ctx, indent=2, cls=_DecimalEncoder))
    return path


def context_to_prompt(ctx: Dict[str, Any]) -> str:
    """
    Convert context to a compact text prompt suitable for LLM input.
    Useful for copy-paste to Perplexity, Claude.ai, etc.
    """
    bs = ctx["balance_sheet"]
    tax = ctx["tax_estimate"]
    entity = ctx["entity"]
    lines = [
        f"# Financial Report: {entity['name']} ({ctx['period']})",
        f"Entity type: {entity['type']} | State: {entity['state']}",
        "",
        "## Balance Sheet",
        f"  Total Assets:      ${bs['total_assets']:>12,.2f}",
        f"  Total Liabilities: ${bs['total_liabilities']:>12,.2f}",
        f"  Total Equity:      ${bs['total_equity']:>12,.2f}",
        f"  Net Income:        ${bs['net_income']:>12,.2f}",
        f"  Balanced:          {bs['is_balanced']}",
        "",
        "## Tax Estimate (Annualized)",
        f"  Annual Net Income:  ${tax['annual_net_income']:>12,.2f}",
        f"  SE Tax (15.3%):     ${tax['se_tax']:>12,.2f}",
        f"  Federal Income Tax: ${tax['federal_income_tax']:>12,.2f}",
        f"  State Income Tax:   ${tax['state_income_tax']:>12,.2f}",
        f"  TOTAL TAX:          ${tax['total_annual_tax']:>12,.2f}",
        f"  Effective Rate:     {tax['effective_rate_pct']:.1f}%",
        "",
        "## Quarterly Payments",
    ]
    for pmt in tax["quarterly_payments"]:
        lines.append(f"  {pmt['quarter']} – {pmt['due_date']}: ${pmt['amount']:,.2f}")

    if "transactions" in ctx:
        lines += ["", f"## Transactions ({len(ctx['transactions'])} total)"]
        for t in ctx["transactions"][:20]:
            lines.append(
                f"  {t['date']}  {t['description'][:40]:<40}  "
                f"${t['amount']:>10,.2f}  [{t['coa_code']}]"
            )
        if len(ctx["transactions"]) > 20:
            lines.append(f"  … and {len(ctx['transactions']) - 20} more")

    return "\n".join(lines)


def _now_iso() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat()


def _safe_div(a, b) -> Optional[float]:
    try:
        return round(float(a) / float(b), 4) if b else None
    except Exception:
        return None
